---
title: "COVID19 Africa response"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    html_preview: false
    toc: true
    toc_depth: 2
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("~/Documents/freightwaves/Africa-covid19-response")) 
library(rtweet)
library(tidyverse)
library(rvest)
theme_set(theme_bw(base_size=20))
```

Load csv of twitter handles,

```{r}
news_sites <- read_csv('data/africa_news_sites_4_6_2020.csv', na = c("null",""," ")) %>%
  set_names(c("news_url", "twitter_handle"))

print(news_sites)
```

To search the handles we need to strip the "@", look up user, and collect the data,

```{r, warning=FALSE, message=FALSE, eval=FALSE}
# clean and prepare handles
handles <- news_sites %>%
  mutate(handle = str_remove(twitter_handle,"@")) %>% # remove @
  drop_na(handle) %>% # remove rows without handles
  pull(handle) # extract handle column

# search twitter posts from handles
twitter_timeline <- get_timelines(handles, n=3200) 

# clean post for analysis 
twitter_posts <- twitter_timeline %>%
  mutate(text=tolower(text)) %>%
  filter(stringr::str_detect(text, 'corona|coronavirus|virus|novel|covid|covid-19|pandemic')) %>%
  select(created_at,screen_name,text,favorite_count,retweet_count,
         hashtags, linked_url=urls_expanded_url) %>% # select specific columns
  unnest(linked_url) %>% # convert url from list to column
  mutate(hashtags = set_names(hashtags, screen_name), # add names to list
         hashtags = map(hashtags, str_c, collapse=", ")) %>% # create char string
  unnest(hashtags) # convert list to column 

# write_csv(twitter_posts %>% slice(1:100),"data/twitter_url_sample.csv")
```

Plot tweets through time,

```{r, fig.width=10,fig.height=7}
twitter_posts <- read_csv("data/twitter_url_complete.csv")

twitter_posts %>%
  mutate(date = lubridate::as_date(created_at)) %>%
  group_by(screen_name, date) %>%
  count() %>%
  filter(n > 25) %>%
  ggplot() +
  geom_line(aes(date,n,color=screen_name)) + 
  labs(y="number of tweets")
```
Download text from one webpage,

```{r}
webpage <- read_html('https://www.nation.co.ke/news/Four-more-test-positive-for-Covid-19-/1056-5508262-mkqe0ez/index.html') %>%
   html_nodes(xpath='/html/body/article/section[2]/section[2]/div/div/article/div/article/section[2]/div[1]/p') %>%      
        html_text() 

print(webpage)
```


